# A React Native Build Workflow
name: Veracode Build Workflow

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
   workflow_dispatch:   
jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      - name: npm
        run: npm --version
      
      - run: ls
      
      - run: npm install --production
      - run: ls
      
      - run: |
          ls ${{ github.workspace }}
          zip -r reactvulna.zip .
          ls
          
      - name: Veracode Dependency Scanning
           # You may pin to the exact commit or the version.
           # uses: veracode/veracode-sca@9ab4d631fc9a0f14e1f9322c0d61bea90e924de1
        uses: veracode/veracode-sca@v2.0.65
        with:
          # Authorization token to query and create issues
          github_token: ${{github.token}} # default is ${{ github.token }}
          # Run the SRCCLR with the `--quick` options
          quick: true # optional, default is false
          # Show update advisor
          update_advisor: true # optional, default is false
          # A git URL to work with in case the scan is not for the current repository
          url: https://github.com/bnreplah/reactvulna # optional, default is 
          # An attribute to instruct the action to create an issue from found vulnerability or just simple text output
          create-issues: false # optional, default is false
          # A path within the repository where the build definition starts
          path: . # optional, default is .
          # Run the SRCCLR in debug mode
          debug: true # optional, default is false
          # Run the SRCCLR with the `--skip-collectors` options
          skip-collectors: false # optional, default is false
          # Run the SRCCLR with the `--allow-dirty` option
          allow-dirty: true # optional, default is false
          # Run the SRCCLR with the `--recursive` option
          recursive: true # optional, default is false
          # Run the SRCCLR with the `--skip-vms` option
          skip-vms: false # optional, default is false

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: reactvulna # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: reactvulna.zip
          # The desired behavior if no files are found using the provided path.
          
          
      - name: Veracode Pipeline-Scan
        # You may pin to the exact commit or the version.
        # uses: veracode/Veracode-pipeline-scan-action@8c25cb8c06c0b2684e896b6d07048ea68ce892b5
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.3
        with:
          # vid
          vid: ${{secrets.VERACODE_API_ID}} 
          # vkey
          vkey: ${{secrets.VERACODE_API_KEY}}
          # Filename of the packaged application to upload and scan.
          file: reactvulna.zip
          # GITHUB_TOKEN or a repo scoped PAT.
          #token: ${{github.token}} # default is ${{ github.token }}
          # Name of the security policy to download as a file. Required only if you want to download the configuration for a custom policy defined by your organization. After downloading the policy, you can provide this file in a subsequent command using the policy_file parameter.
          #[Optional]
          #request_policy: # optional
          # Fail the pipeline job if the scan finds flaws of the specified severities. Enter a comma-separated list of severities in quotation marks.
          
          #fail_on_severity: # optional
          # Fail the pipeline job if the scan finds flaws of the specified CWEs. Enter a comma-separated list of CWE IDs.
          
          #fail_on_cwe: # optional
          # Filter the flaws that exist in the specified baseline file and show only the additional flaws in the current scan.
          
          #baseline_file: # optional
          # Name of the Veracode default policy rule to apply to the scan results. You can only use this parameter with a Veracode default policy.
          
          #policy_name: # optional
          # Name of the local policy file you want to apply to the scan results. To download this file, use the --request_policy parameter.
          
          #policy_file: # optional
          # Amount of time, in minutes, for the Pipeline Scan to wait before reporting an unsuccessful scan if the scan does not complete. Default is 60 minutes, which is also the maximum value.
          
          #timeout: # optional
          # Enter true to show detailed messages for each issue in the results summary.
          
          #issue_details: # optional
          # Enter true to show a human-readable results summary on the console. Default is true.
          
          summary_display: true # optional
          # Enter true to show the JSON containing the scan results on the console. Default is false.
          json_display: false # optional
          
          # Enter true to display detailed messages in the scan results. Default is false.
          verbose: false # optional
          # Enter true to save the scan results as a human-readable file. Default is false.
          
          summary_output: false # optional
          # Enter the filename of the scan results summary file. The file is stored in the current directory. Default is results.txt.
          #summary_output_file: results.txt # optional
          # Enter true to save the scan results in JSON format. Default is true.
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: baseline # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: results.json
          # The desired behavior if no files are found using the provided path.
          
