# A React Native Build Workflow
name: Veracode Build Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      - name: npm
        run: npm --version
      
      - run: ls
      
      - run: npm install --production
      - run: ls
      
      - run: |
          ls ${{ github.workspace }}
          zip reactvulna.zip ${{ github.workspace }}
          unzip reactvulna.zip
          ls
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: reactvulna # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: reactvulna.zip
          # The desired behavior if no files are found using the provided path.
      
