# A React Native Build Workflow
name: Veracode Build Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: npm
        run: npm --version
      
      - run: ls
      
      - run: npm run build
      
